### ISSUE TITLE
[OTHER] Segnalazioni RP

### ISSUE THREAD

**Issue by lorenzodeinegri** [RedRoundRobin/swe-docs#331]
- [x] Registro delle modifiche: modificare le regole di versionamento, per evitare che l'approvazione per il rilascio determini uno scatto di indice maggiore, senza che ci siano modifiche.
> Si potrebbe rimuovere la x da x.y.z, però bisogna pensare come tenere aggiornata l'ultima baseline in caso di approvazioni distanti dalla consegna.

- [x] Metiche banali: bisogna aggiungere le nuove metriche per la codifica, oltre che amplicare la sezione di codifica stessa e degli strumenti di supporto.
> Bisogna anche ricordarsi dei test.
> Valutare se ci sono altre cose da aggiungere alle norme.

- [x] Aggiungere visione d'insieme alla pianificazione: bisogna capire bene cosa intenda Tullio e quindi come modificare il tutto.
> Potrebbe essere utile inviare una mail e/o fissare un incontro.

- [x] Casi d'uso: specificare meglio i casi d'uso per la gestione dei gaterway per renderli simili, per profondità di analisi, a quellli per la gestione dei dispositivi.
> Ricordarsi poi di aggioranare i requisiti, le fonti, il tracciamento e i test di sistema.

- [x] UC1: spostare la gerarchia da UC1.1 a UC1 stesso, rimuovendo il diagramma e portando ad un livello superiore tutti i sotto casi d'uso. Inoltre è necessario spostare le estensioni di UC1.1 in UC1.

- [x] UC1.3.3: rimuovere l'attore secondario Telegram, in quanto non aiuta in alcun modo all'inserimento del codice di autenticazione, ma serve solo ad inviarlo all'utente; infatti il caso d'uso riguarda solamento l'inserimento del codice, quindi Telegram non è coinvolto. Di conseguenza deve essere rimosso a casacata nei casi d'uso superiori.

- [x] UC14: modificare il caso d'uso lasciando il solo sotto caso UC14.1 e relative estensioni.

- [x] UC14.2: rimuovere il caso d'uso in quanto è un dettaglio implementativo e non una funzionalità offerta all'utente, come per l'autenticazione sulla web app.

- [x] RA-P-2: specificare meglio il requisito, definendo la struttura hardware dell'architettura, in termini di numero di nodi e di specifiche tecniche, e come i diversi componenti vengono messi in produzione sugli stessi (TODO dopo la progettazione).

> Ricordarsi poi di aggioranare le fonti, il tracciamento e i test di sistema.

**Comment by lorenzodeinegri** [comment]
## Registro delle modifiche

L'idea sarebbe la seguente:
- z: rimane invariata, quindi singole modifiche o aggiunte con contestuale verifica;
- y: utilizzata per l'approvazione di singole sezioni, modifiche o aggiunte in un arco di tempo ristretto;
- x: utilizzata per l'approvazione del documento in toto, la quale determina un insieme di modifiche che non sono più retrocompatibili con le versioni precedenti.

**Comment by lorenzodeinegri** [comment]
## Pianificazione

L'idea per dare una visione d'insieme alla pianificazione, e tenerne sotto controllo le risorse necessarie, è quella di individuare delle macro-fasi.
Queste macro-fasi devono raggruppare più incrementi (che sono a loro volta delle fasi) in base a degli obiettivi a livello di prodotto (alto livello), che possono essere quindi complementari e/o sovrapposti tra loro.
Inoltre, ognuna di queste macro-fasi deve avere una propria pianificazione (diagrammi di Gantt), un proprio preventivo (tempi e costi) e un proprio consuntivo (tempi e cosi) con relativo preventivo a finire.

**Comment by Maxelweb** [comment]
## Domande ulteriori

- Cosa faremo per lo stage?
- Come sarà l'esame?

**Comment by Maxelweb** [comment]
## Domanda per Cradin 🍺 👶 

- RA-P-2 , anche sentendo l'ultima lezione sulla architettura a microservizi, volevamo capire meglio come andare a definire il "deployment".
> Il sistema deve poter gestire un carico di almeno 30 utenti connessi contemporaneamente nella web app
 
### Design pattern che abbiamo adottato

- A partire dalla nostra architettura, noi abbiamo 5 componenti, tra cui gateway con un device simulator, adapter per i database, servizio API e due applicazioni che comunicano con l'utente, ossia webapp e telegram bot. Rispetto quanto riportato a lezione, non abbiamo trovato particolari attinenze con le architetture a microservizi, pur usando di Kafka. Al massimo, ci è parso di avere una somiglianza con il centralized message topology, che fa uso del broker, ma in ogni caso noi facciamo anche uso delle API per le richieste di webapp e bot telegram, quindi ci pare più una archiettura mista.

**Comment by lorenzodeinegri** [comment]
**RA-P-2**
- Ogni requisito deve essere verificabile, quindi se non vengono messi dei vincoli minimi per il soddisfacimento è rischioso
- Si può togliere il requisito, oppure vanno specificate per bene tutte le caratteristiche hw

**Architettura**
- Microservizi che operano sulla base di eventi
- Architettura ad eventi o a microservizi si differenziano per organizzazione aziendale
- In realtà ogni microservizio è un app a sè stante che funziona da sola, poi componendo i vari microservizi si ottengono le funzionalità
> TODO: guardare event driven microservices architecture

**Design Pattern**
- Generale
	- Non bisogna cercare i design pattern, ma si intruducono solo quando vanno a risolvere dei problemi che vengono riscontrati nel far interagire le classi

- Gateway
	- Al posto di Vanilla Kafka si poteva usare Spring Kafka
	- Il consumer deve scatenare qualcosa, perché essendo concorrente rischia inconsistenza
	- Consumer legge e quando legge la configurazione fa partire un task su un thread o in modo sincrono fa aggiornare la configurazione

- API
	- Usare bene Spring
	
**Manuale del manutentore**
- Tutte informazioni per chi deve modificare o far evolvere il sw
- Se le info che sono utili per chi deve mettere mano sul sw allora vanno messe e devono essere ben contestualizzate

**PB**
- 15 minuti in cui bisogna spiegare architetturalmente il sw, come è stato pensato e come viene sviluppato dal punto di vista architetturale
- Libertà assoluta per materiali, non bisogna andare nè troppo nel dettaglio nè troppo a visione generale
- Non diagrammi delle classi con tutte le classi e moltissime associazioni
- Diagrammi ristretti sulle parti più salienti
- Architettura logica: quali sono le varie parti del sistema e come interagiscono

**Comment by lorenzodeinegri** [comment]
**Ulteriori appunti riguardo le segnalazioni di Cardin**

- I diagrammi dei package vanno fatti uno per componente per vedere bene le dipendenze tra classi
- Gli observer non sono da esplicitare, perché integrati nei framework, ma vanno saputi spiegare e motivare
- Bisogna usare una strategia bottom-up, partendo dalle classi, si fanno interagire tra loro e, se sorgono problemi, probabilmente c'è un design pattern che può aiutare a risolverli
- Il principio da utilizzare per i diagrammi dei package non importa, basta fare vedere bene le classi e le dipendenze
- I diagrammi delle attività vanno fatti solo per processi principali, quindi per cose che hanno bisogno di più spiegazione e se sono molto significative, altrimenti non servono
  - Per ogni diagramma non ci devono essere più di 8-10 azioni
- I diagrammi di sequenza vanno fatti solo per classi e metodi implementati in esse, quindi quando bisogna descrivere determinate operazioni mostrando bene tutti i passaggi temporali tra le varie classi
  - Vanno usati solo per cose importanti e rilevanti
  - Sono più importanti di quelli di attività
