### ISSUE TITLE
[OTHER] RIferimenti esterni manuale sviluppatore

### ISSUE THREAD

**Issue by lorenzodeinegri** [RedRoundRobin/swe-docs#391]
Aggiungere i riferimenti ai documenti "bug risolti" e "documentazione API" nel manuale del manutentore.

**Comment by aletomm** [comment]
Nel diagramma delle classi della componente \glock{web app}, rappresentato nel file \textit{Immagini/WebApp-Classi.png}, sono presenti principalmente i provider ed i controller:... @Maxelweb
